### PR TITLE
adding errors header

### PR DESCRIPTION
**Pull request by edgarriba**
solving that:

CV_Error(CV_StsNotImplemented, "Not implemented method because it's not efficient to split feature detection and description extraction here\n");

### CODE REVIEW

**Comment by vrabaud** [comment]
which OpenCV3 are you using ? The .deb from ROS or your own ?

**Comment by edgarriba** [comment]
deb

**Comment by vrabaud** [comment]
weird, it works for me in a clean workspace. Which exact version of the deb ? which ROS / Ubuntu distro ?

**Comment by edgarriba** [comment]
indigo + kubuntu 14.04

**Comment by vrabaud** [comment]
Which exact version of the deb ?

**Comment by edgarriba** [comment]
riba@gari-linux:~/Datasets/bags_ork$ apt-cache policy ros-indigo-opencv3
ros-indigo-opencv3:
  Instaŀlat: 2.9.2-2trusty-20141229-2205-+0000
  Candidat:  2.9.2-2trusty-20141229-2205-+0000
  Taula de versió:
 *** 2.9.2-2trusty-20141229-2205-+0000 0
        500 http://packages.ros.org/ros/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by vrabaud** [comment]
ok. 2.9.4 got released, please update. But I did provide a proper fix.

**Comment by edgarriba** [comment]
oki!

**Pull request closed without merging**
